merge: stashed changes

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -42,8 +42,8 @@ execution_role=${BUILDKITE_PLUGIN_ECS_DEPLOY_EXECUTION_ROLE:-""}
 region=${BUILDKITE_PLUGIN_ECS_DEPLOY_REGION:-""}
 requires_compatibilities=${BUILDKITE_PLUGIN_ECS_DEPLOY_REQUIRES_COMPATIBILITIES:-""}
 network_mode=${BUILDKITE_PLUGIN_ECS_DEPLOY_NETWORK_MODE:-""}
-task_cpu=${BUILDKITE_PLUGIN_ECS_DEPLOY_CPU:-""}
-task_memory=${BUILDKITE_PLUGIN_ECS_DEPLOY_MEMORY:-""}
+task_cpu=${BUILDKITE_PLUGIN_ECS_DEPLOY_FARGATE_CPU:-""}
+task_memory=${BUILDKITE_PLUGIN_ECS_DEPLOY_FARGATE_MEMORY:-""}
 
 if [[ $region != "" ]]; then
   # shellcheck disable=SC2034 # Used by the aws cli
@@ -76,7 +76,7 @@ function create_service() {
     target_group_arguments=$(generate_target_group_arguments "$5" "$6" "$7")
 
     # shellcheck disable=SC2016
-    service_defined=$(aws ecs describe-services --cluster "$cluster_name" --service "$service_name" --query 'services[?status==`ACTIVE`].status' --output text |wc -l)
+    service_defined=$(aws ecs describe-services --cluster "$cluster_name" --service "$service_name" --query 'services[?status==`ACTIVE`].status' --output text | wc -l)
     if [[ $service_defined -eq 0 ]]; then
         echo "--- :ecs: Creating a Service $service_name in cluster $cluster_name"
         # shellcheck disable=SC2086
@@ -86,7 +86,7 @@ function create_service() {
         --task-definition "$task_definition" \
         --desired-count "$desired_count" \
         --deployment-configuration "maximumPercent=${max_deploy_perc},minimumHealthyPercent=${min_deploy_perc}" \
-        $target_group_arguments
+        $target_group_arguments | jq '.'
     fi
 }
 
@@ -129,7 +129,7 @@ register_command="aws ecs register-task-definition \
     --container-definitions '$container_definitions_json'"
 
 if [[ -n "${task_role_arn}" ]]; then
-    register_command+=" --task-role-arn ${task_role_arn}"
+    register_command+=" --task-role-arn ${task_role_arn} | jq '.'"
 fi
 
 if [[ -n "${execution_role}" ]]; then
@@ -170,7 +170,7 @@ echo "Registered ${task_family}:${task_revision}"
 create_service "$cluster" "${task_family}:${task_revision}" "$service_name" "$desired_count" "$target_group" "$target_container" "$target_port"
 
 # shellcheck disable=SC2016
-lb_config=$(aws ecs describe-services --cluster "$cluster" --services "$service_name" --query 'services[?status==`ACTIVE`]' |jq -r '.[0].loadBalancers[0]')
+lb_config=$(aws ecs describe-services --cluster "$cluster" --services "$service_name" --query 'services[?status==`ACTIVE`]' | jq -r '.[0].loadBalancers[0]')
 error="+++ ^^^
 +++ Cannot update a service to add/remove a load balancer. First delete the service and then run again, or rename the service to force a new one to be created"
 
@@ -199,26 +199,102 @@ fi
 echo "--- :ecs: Updating service for ${service_name}"
 echo "for cluster: ${cluster}"
 echo "revision: ${task_family}:${task_revision}"
-aws ecs update-service --cluster "${cluster}" --service "${service_name}" --task-definition "${task_family}:${task_revision}" > /dev/null
+
+aws ecs update-service \
+  --cluster "${cluster}" \
+  --service "${service_name}" \
+  --task-definition "${task_family}:${task_revision}" | jq '.'
+
+############################################################
+# Script begins                                            #
+# https://github.com/misterjoshua/ecs-deployment-wait      #
+############################################################
+
+function log() {
+    echo "$1" >&2
+}
+
+function die() {
+    log "$1"
+    exit 1
+}
+
+function describeService() {
+    SERVICE=$(aws ecs describe-services --cluster "$cluster" --services "$service_name")
+    serviceIsValid <<<"$SERVICE" || return 1
+    cat <<<"$SERVICE"
+}
+
+function serviceIsValid() {
+    [ "true" = "$(jq '.services | length > 0')" ]
+}
+
+function serviceNumPrimary() {
+    jq '[ .services[].deployments[] | select(.status == "PRIMARY") | .runningCount ] | add // 0' --raw-output
+}
+
+function serviceNumActive() {
+    jq '[ .services[].deployments[] | select(.status == "ACTIVE") | .runningCount ] | add // 0' --raw-output
+}
+
+function serviceNumTotal() {
+    jq '[ .services[].deployments[] | .runningCount ] | add // 0' --raw-output
+}
+
+function serviceIsStable() {
+    [ "true" = "$(jq '([.services[].deployments[]] | length == 1) and ([.services[].deployments[] | select(.runningCount == .desiredCount)] | length == 1)')" ]
+}
+
+function now() {
+    date +%s
+}
+
+function waitForDeployment() {
+    TIMEOUT=${TIMEOUT:-600}
+    INTERVAL=${INTERVAL:-10}
+
+    log "Started: Time=$(date), Timeout=$TIMEOUT seconds"
+
+    START_TIME=$(now)
+    while true; do
+        SERVICE=$(describeService)
+        (( $? == 0 )) || die "Couldn't describe the service."
+
+        NUM_PRIMARY=$(serviceNumPrimary <<<$SERVICE)
+        NUM_ACTIVE=$(serviceNumActive <<<$SERVICE)
+        NUM_TOTAL=$(serviceNumTotal <<<$SERVICE)
+        let "ELAPSED=$(now) - START_TIME"
+
+        log "Deployment task counts: Primary=$NUM_PRIMARY, Active=$NUM_ACTIVE, Total=$NUM_TOTAL; Elapsed: $ELAPSED seconds"
+
+        if serviceIsStable <<<$SERVICE; then
+            # Deployment finished
+            return 0
+        elif (( ELAPSED > TIMEOUT )); then
+            log "Timeout $TIMEOUT seconds. (actual: $ELAPSED)"
+            return 1
+        else
+            # Deployment not done yet. Check again in a bit.
+            sleep $INTERVAL
+        fi
+    done
+}
 
 ## Now we wait till it's stable
 echo "--- :ecs: Waiting for services to stabilize"
-deploy_exitcode=0
-aws ecs wait services-stable \
-  --cluster "${cluster}" \
-  --services "${service_name}" || deploy_exitcode=$?
 
+exit_code=$( (waitForDeployment && log "Deployment finished." && exit 0) || die "Deployment didn't succeed." )
 
 service_events=$(aws ecs describe-services \
   --cluster "${cluster}" \
   --service "${service_name}" \
   --query 'services[].events' --output text)
 
-if [[ $deploy_exitcode -eq 0 ]]; then
+if [[ $exit_code -eq 0 ]]; then
   echo "--- :ecs: Service is up 🚀"
   echo "$service_events"
 else
   echo "+++ :ecs: Service failed to deploy ❌"
   echo "$service_events"
-  exit $deploy_exitcode
+  exit $exit_code
 fi
